sudo: required
language: bash
language: python

python:
  - "2.7"
# command to install dependencies
install:
  - pip install pipreqs
  - pipreqs .
  - pip install -r ./requirements.txt
before_script:
  - chmod +x start-server.sh
  - ./start-server.sh
script:
  # Network Information
  - current_ip="$(curl --silent --show-error --fail ipecho.net/plain)"
  - echo "Public IP :$current_ip"
  - netstat -ntlp | grep LISTEN  
after_script:
  - chmod +x start-client.sh
  - ./start-client.sh