
sudo: required
language: python
python:
- 2.7

install:
- pip install pipreqs

script:
- pipresq .
- pip install -r requirement.txt

# Network Information
- current_ip="$(curl --silent --show-error --fail ipecho.net/plain)"
- echo "Public IP :$current_ip"

- python server.py
