sudo: required
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install pipreqs
  - pipreqs .
  - pip install -r ./requirements.txt
before_script:
  - sudo ./start-server.sh
script:
  # Network Information
  - current_ip="$(curl --silent --show-error --fail ipecho.net/plain)"
  - echo "Public IP :$current_ip"
  - netstat -ntlp | grep LISTEN  